### ISSUE TITLE
won't publish when naming project with underscores

### ISSUE THREAD

**Issue by jondot** [sdispater/poetry#142]
When creating a new project like this

    $ poetry new foo_bar

Poetry package naming (_package.name in publisher, for example) will look for `foo-bar`, while the tarballs will be `foo_bar...tar.gz`.

This makes Poetry fail silently as if it succeeded (there is a 'TODO check existence' right above there, so I guess if implemented that would be done).

For now, I'm going to create new projects like so:

    $ poetry new foo-bar

**Comment by sdispater** [comment]
The `0.10.0a3` prerelease should fix this issue. You might want to give it a try :-)

**Comment by sdispater** [comment]
Release `0.10.0` is out and should fix this issue.

**Comment by kentprimrose** [comment]
I still have this issue with version 0.12.15. Received a runtime error indicating that "[RuntimeError]
"foo-bar-0.1.0.tar.gz" does not exist." However, after creating another project named "foo-bar" (per the suggestion above), and publishing it to a local devpi instance (which succeeded), I'm now able to publish from foo_bar just fine as well. In the devpi web interface, I can see that "foo-bar" (and ONLY "foo-bar" was created.
