### ISSUE TITLE
cleo and clikit upgrade break poetry

### ISSUE THREAD

**Issue by itajaja** [sdispater/poetry#1497]
cleo was released an hour ago, and it was a minor change, but includes a breaking change from clikit. since clikit is used **directly** in poetry, clikit should not be a transitive dependency, but an actual depenendecy in this poetry's pyproject.toml. The issue for now is to install the previous version of cleo before installing poetry.

cc @c0state

**Comment by erj1** [comment]
+1

**Comment by sdispater** [comment]
I just published a `1.0.0b3` release that should fix the issue.

Note that only the `1.0` prereleases were affected since previous versions are using a version of `cleo` that does not depend on `clikit`.

**Comment by itajaja** [comment]
thanks @sdispater !

**Comment by hvdklauw** [comment]
This does not fix it for us.

We still can't upgrade past 1.0.0a5 because of #1313 which we need because of #338 

Using poetry to install the packages really isn't an option because it makes our CI times way longer then they need to be.

I love the way poetry works, but I think we need to start looking at alternatives (again).
