### ISSUE TITLE
Poetry does not extract dependencies from .zip (or .tar.bz2) sdists

### ISSUE THREAD

**Issue by gmacon** [sdispater/poetry#316]
- [x] I am on the [latest](https://github.com/sdispater/poetry/releases/latest) Poetry version.
- [x] I have searched the [issues](https://github.com/sdispater/poetry/issues) of this repo and believe that this is not a duplicate.
- [ ] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option).

I found https://github.com/sdispater/poetry/issues/301#issuecomment-405649519, which explains how dependency extraction is supposed to work. However, I think I'm seeing an issue with a different root cause. More on that in a minute.

- **OS version and name**: macOS 10.12.6
- **Poetry version**: 0.11.2
- **Link of a [Gist](https://gist.github.com/) with the contents of your pyproject.toml file**: https://gist.github.com/gmacon/57c08a2a28d82f4cfe8a0b634cc2259e

## Issue

Calling `poetry lock` does not install `networkx`'s dependency `decorator`. Following what's supposed to happen:

1. Check PyPI for `requires_dist`: networkx has no information
2. Download a wheel: there are no wheels
3. Download an sdist and extract it: `networkx-2.1.zip`, ok
4. Read the `networkx-2.1/*.egg-info/requires.txt` file: but poetry doesn't find it.

It looks like the issue is here: https://github.com/sdispater/poetry/blob/1b7492e5659a43c0a05f10c6d60e90603c6c3406/poetry/repositories/pypi_repository.py#L426

This doesn't work correctly for networkx because the file name does not end with the characters `.agrtz`, and so it looks for the file `networkx-2.1.zip/*.egg-info`, which, of course, doesn't exist.

I have a patched version, and I'm happy to open a PR for it, but I was wondering what level of tolerance there would be to rewriting this function in a more major way than the minimum required to fix the bug. First, I wondered why there are two separate calls to `sdist_dir.glob`. Is this for performance reasons or something else? Also, I was curious about the decision to unpack to disk. Why not just use the ZipFile/TarFile API to extract just the one file we need?

**Comment by sdispater** [comment]
This is fixed in the latest release: `0.11.3`

**Comment by hwinroth** [comment]
As far as I can see, the decorator dependency of networkx is still not installed by poetry 0.11.4. The source code line highlighted by gmacon has not been changed in 0.11.4? Was this bug closed by mistake?

**Comment by sdispater** [comment]
@hwinroth Did you clear your cache?

```
poetry cache:clear pypi --all
```
